<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:Manitoba_Hydro_Current_Power_Outages_WFS="https://dservices2.arcgis.com/QoeQkfdOG126FqSi/arcgis/services/Manitoba_Hydro_Current_Power_Outages_WFS/WFSServer" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:gml="http://www.opengis.net/gml/3.2" targetNamespace="https://dservices2.arcgis.com/QoeQkfdOG126FqSi/arcgis/services/Manitoba_Hydro_Current_Power_Outages_WFS/WFSServer" elementFormDefault="qualified" attributeFormDefault="unqualified">
<xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
<xsd:element name="MH_Current_Power_Outages" type="Manitoba_Hydro_Current_Power_Outages_WFS:MH_Current_Power_OutagesFeatureType" substitutionGroup="gml:AbstractFeature"/>
<xsd:complexType name="MH_Current_Power_OutagesFeatureType">
  <xsd:complexContent>
    <xsd:extension base="gml:AbstractFeatureType">
      <xsd:sequence>
        <xsd:element minOccurs="0" maxOccurs="1" name="Shape" nillable="true" type="gml:MultiSurfacePropertyType"/>
        <xsd:element minOccurs="0" maxOccurs="1" name="OBJECTID" type="xsd:int"/>
        <xsd:element minOccurs="0" maxOccurs="1" name="Outage_ID" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="25"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="Outage_Type" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="50"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="Time_of_Outage" nillable="true" type="xsd:dateTime"/>
        <xsd:element minOccurs="0" maxOccurs="1" name="Customers_without_power" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="25"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="Customers_without_power_" nillable="true" type="xsd:int"/>
        <xsd:element minOccurs="0" maxOccurs="1" name="ETR" nillable="true" type="xsd:dateTime"/>
        <xsd:element minOccurs="0" maxOccurs="1" name="Cause" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="Subcause" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="Crew_Status" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="255"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="Field_Verified_ETR" nillable="true">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="3"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="1" name="Data_Last_Updated" nillable="true" type="xsd:dateTime"/>
        <xsd:element minOccurs="0" maxOccurs="1" name="Area" nillable="true" type="xsd:double"/>
        <xsd:element minOccurs="0" maxOccurs="1" name="Shape__Area" nillable="true" type="xsd:double"/>
        <xsd:element minOccurs="0" maxOccurs="1" name="Shape__Length" nillable="true" type="xsd:double"/>
      </xsd:sequence>
    </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>
</xsd:schema>
